config/routes.rb
Rails.application.routes.draw do

  root "users#log_in"
  resources :users, only: [:new, :create]
  resources :menu_items
  resources :parties do
    resource :order do
      post   'menu_items' => 'orders#add_menu_item',    as: :add_menu_item_to
      delete 'menu_items' => 'orders#remove_menu_item', as: :remove_menu_item_from
    end
  end

  get '/users/log_in' => "users#log_in", as: :log_in
  get '/admin' => "pages#admin", as: :admin
  get '/server' => "pages#server", as: :server

  post    '/sessions' => "sessions#create", as: :create_session
  delete  '/sessions' => "sessions#destroy", as: :destroy_session
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  has_and_belongs_to_many :orders
end

app/models/menu_items_orders.rb
class MenuItemsOrders < ActiveRecord::Base
  belongs_to :menu_item
  belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :party
  has_and_belongs_to_many :menu_items
  # has_many :menu_items, through: :menu_items_orders

  def total_price
    menu_items.map(&:price).sum
  end
end

app/models/party.rb
class Party < ActiveRecord::Base
  belongs_to :user
  has_one :order

  after_create :create_order

  private

  def create_order
    Order.create(party: self)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  def new
    @menu_item = MenuItem.new
  end

  def create
    menu_item = MenuItem.create menu_item_params
    redirect_to admin_path
  end

  private
  
  def menu_item_params
    params.require(:menu_item).permit(:name, :kind, :price)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :find_party

  def show
    @order = @party.order
  end

  def edit
    @order = @party.order

    menu_items = MenuItem.all

    @menu = menu_items.group_by{|item| item.kind}
  end

  def update
    @order = Order.new(params[:order])
  end

  def add_menu_item
    menu_item = MenuItem.find params[:menu_item_id]

    @party.order.menu_items << menu_item if menu_item

    redirect_to action: :edit
  end

  def remove_menu_item
    line_item = MenuItemsOrders.where(order: @party.order, menu_item: params[:menu_item_id]).first
    
    line_item.destroy if line_item
 
    redirect_to action: :edit
  end

  private

  def find_party
    @party ||= Party.find params[:party_id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include SessionsHelper

  before_filter :authenticate_admin!, only: :admin
  before_filter :authenticate!, only: :server

  def admin
  end

  def server
    @parties = Party.where(user: current_user)
  end


end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  include SessionsHelper

  before_filter :authenticate!

  def new
    @party = Party.new
  end

  def create
    _params = party_params.merge(user: current_user)

    party = Party.create _params
    redirect_to server_path
  end

  def destroy
  party = Party.find(params[:id])
  party.destroy
  redirect_to server_path
end

  private

  def party_params
    params.require(:party).permit(:name, :table_number)
  end
end

app/controllers/servers_controller.rb
class ServerController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # take the username and password and confirm that this is a user on my site
  def create
    username = params[:username]
    password = params[:password]

    user = User.find_by username: username

    if user && user.authenticate( password )
      session[:user_id] = user.id

      if user.admin
        redirect_to admin_path
      else
        redirect_to server_path
      end
    else
      redirect_to log_in_path
    end
  end

  # destroy a session
  def destroy
    session[:user_id] = nil
    redirect_to log_in_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include SessionsHelper

  before_filter :authenticate_admin!, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    user = User.create user_params
    redirect_to admin_path
  end

  def log_in

  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :admin)
  end
   
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/administrator_helper.rb
module AdministratorHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/server_helper.rb
module ServerHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def authenticate!
    redirect_to log_in_path unless current_user
  end

  def authenticate_admin!
    redirect_to log_in_path unless current_user && current_user.admin
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestaurantProject</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.css" media="screen" title="no title" charset="utf-8">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/menu_items/new.html.erb
<h1>New Menu Item</h1>

<div class="new">
  <div class="container">
    <div class="row">
      <%= form_for @menu_item do |f| %>
      <div class="one column">
        <%= f.label :name %>
      </div>
      <div class="three columns">
        <%= f.text_field :name %>
      </div>
      <div class="one column">
        <%= f.label :kind %>
      </div>
      <div class="three  columns">
        <%= f.text_field :kind %>
      </div>
      <div class="one column">
        <%= f.label :price %>
      </div>
      <div class="two columns">
        <%= f.text_field :price %>
        <%= f.submit %>
      </div>
      <% end %>
      <div class= "row">
        <div class= "one column">
        </div>
        <div class="five columns"
          <a><%= link_to "Back to Administration Station", admin_path %></a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/orders/edit.html.erb
<div class="container">
  <div class="row">
    <div class="nine columns">
      <h1>Order Station</h1>
    </div>
    <div class="three columns">
      <h1>Order</h1>
    </div>
  </div>
  <div class="row">
      <% @menu.each do |category, items| %>
      <div class="three columns">
        <h2><%= category %></h2>
          <% items.each do |item| %>
            <p> <%= item.name %> <%= button_to "", add_menu_item_to_party_order_path(@party), method: :post, params: { menu_item_id: item.id }, class: 'add_button'%></p>
            <% end %>
      </div>
      <% end %>
    <div class="three columns">
      <h2>Ticket</h2>
      <% @party.order.menu_items.each do |item| %>
        <p> <%= item.name %> <%= button_to "", remove_menu_item_from_party_order_path(@party), method: :delete, params: { menu_item_id: item.id }, class: 'remove_button'%> </p>
    <% end %>
    </div>
  </div>
  <div class="row">
    <div class="three columns"
      <p><a><%= link_to "Back to Your Work Station", server_path %></a></p>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<h1>Receipt</h1>

<ul>
  <% @order.menu_items.each do |item| %>
  <li><%= item.name %> - <%= number_to_currency item.price %></li>
  <% end %>


<li><strong>Total:</strong> <%= number_to_currency @order.total_price %></li>
<li><a><%= link_to "Back to Your Work Station", server_path %></a></li>
</ul>

app/views/pages/admin.html.erb
<h1>Admin Page</h1>
  <ul>
    <li> <%= link_to "New User", new_user_path %> -
    <%= link_to "New Menu Item", new_menu_item_path %></li>
    <li><%= link_to "Logout", destroy_session_path, method: :delete %></li>

app/views/pages/server.html.erb
<h1>Your Work Station</h1>
  <ul>
  <% @parties.each do |party| %>
      <li> <%= party.name %> -
      <a><%= link_to "Edit Order", edit_party_order_path(party) %></a> -
      <a><%= link_to "Delete Party", party_path(party), method: :delete %></a> -
      <a><%= link_to "Receipt", party_order_path(party) %></a> </li>
  <% end %>

<li><a><%= link_to "New Party", new_party_path %></a></li>
<li><a><%= link_to "Logout", destroy_session_path, method: :delete %></a></li>

app/views/parties/new.html.erb
<h1>New Party</h1>
<div class="new">
  <div class="container">
    <div class="row">
      <%= form_for @party do |f| %>
      <div class="one column">
        <%= f.label :name %>
      </div>
      <div class="three columns">
        <%= f.text_field :name %>
      </div>
      <div class="two columns">
        <%= f.label :table_number %>
      </div>
      <div class="two columns">
        <%= f.text_field :table_number %>
      </div>
      <div class="one column">
        <%= f.submit %>
      </div>
    </div>
    <div class="row">
      <div class= "one column">
      </div>
      <div class="three columns"
          <a><%= link_to "Back to Parties", server_path %></a>
      </div>
    </div>
  </div>
  </div>

<% end %>

app/views/users/log_in.html.erb
<h1>Please Submit Your Credentials</h1>

<%= form_tag '/sessions', method: :post do %>
  <div class="log_in">
    <div class= "container">
      <div class= "row">
        <div class= "two columns">
          <%= label_tag :username %>
        </div>
        <div class= "three columns">
          <%= text_field_tag :username %>
        </div>
        <div class= "two columns">
          <%= label_tag :password %>
        </div>
        <div class= "three columns">
          <%= password_field_tag :password %>
        </div>
        <div class= "two columns">
          <%= submit_tag "Log In" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Add a User</h1>
<div class="new"
  <div class= "container">
    <div class="row">
      <%= form_for @user do |f| %>
      <div class="one column">
        <%= f.label :username %>
      </div>
      <div class="two columns">
        <%= f.text_field :username %>
      </div>
      <div class="one column">
        <%= f.label :email %>
      </div>
      <div class="two columns">
        <%= f.text_field :email %>
      </div>
      <div class="one column">
        <%= f.label :password %>
      </div>
      <div class="two columns">
        <%= f.password_field :password %>
      </div>
      <div class="one column">
        <%= f.label :admin %>
      </div>
      <div class="one column">
        <%= f.check_box :admin %>
      </div>
      <div class="two columns">
        <%= f.submit %>
      </div>
      <% end %>
    </div>
    <div class= "row">
      <div class= "one column">
      </div>
      <div class="five columns"
        <a><%= link_to "Back to Administration Station", admin_path %></a>
      </div>
    </div>
  </div>
</div>